name: TNT_Tag
version: ${project.version}
main: me.cryptizism.tnttag.TntTag
authors: [ Cryptizism ]
depend: [ ProtocolLib ]
commands:
  it:
    description: Makes you become IT
    usage: /<command> [target]
  start:
    description: Force starts the game
    usage: /<command>
  set-map:
    description: Sets the maps spawn Location
    usage: /<command> [x] [y] [z]
  set-spawn:
    description: Sets the pre-game spawn
    usage: /<command> [x] [y] [z]
  set-holo:
    description: Sets the hologram leaderboards location
    usage: /<command> [x] [y] [z]
  spectate:
    description: Makes you or another player spectate
    usage: /<command> [target]
  set-variables:
    description: Sets variables for the
    usage: /<command> variable value